### ISSUE TITLE
Page "Exporting Game Files":  AssetRipper Version is Not Work for New Game Version

### ISSUE THREAD

**Issue by Lu-233** [Timberborn-Modding-Central/TimberAPI_Docs#15]
in page: documentation/getting_started/making_mods/exporting_game_files/index.md
https://github.com/Timberborn-Modding-Central/TimberAPI_Docs/blob/7a29cdd043a2c342071026aab59b911ccc250a45/documentation/getting_started/making_mods/exporting_game_files/index.md?plain=1#L20-L21

it works for older game v0.2, but get error for v0.3

I tried AssetRipper new version 0.2.4.2, it works but still got some error in console.

**Comment by KnatteAnka** [comment]
Since V0.3.4.3 of timberborn it need to use newer version of AssetRipper 
Have tried prerelease version 0.3.0.0 and it show no error
also MonoScript is now called Plugins.

cant get Git to restore a branch of my fork to get back to main doc so cant do the pull request atm :(
